### ISSUE TITLE
Mob verschwindet beim Ändern des Namens und Reload

### ISSUE THREAD

**Issue by JBou** [Howaner/FakeMobs#2]
Wenn ich einen FakeMob Player spawne, diesen auswähle und dann den Namen ändere, verschwindet er. Wenn ich dann nochmal den Namen ändere, taucht er kurz auf und verschwindet dann sofort wieder. Erst nach einem Reload ist er wieder sichtbar (Aber auch oft buggy -> siehe nächsten absatz). Dies passiert bei anderen Mobs außer dem Player nicht .

Außerdem verschwinden auch nach einem normalen Reload manchmal die Mobs (zufällig, egal welcher EntityType). Nach den Reloads taucht, wie beim erster Bug, der FakeMob kurz auf und verschwindet dann sofort wieder.

In der Console werden keine Fehler ausgegeben. Gestestet auf der neuesten Spigot und ProtocolLib Version.

MfG JBou

**Comment by Howaner** [comment]
Ah, das ist ein Bug im 1.8 Client.
Kennt der Client bereits ein Entity mit der bestimmten ID und du schickst erneut das Spawn Paket, dann wird das Entity unsichtbar.
In Minecraft 1.7 wurde das Entity einfach überschrieben.

Ich fixx das in den nächsten Tagen :)

**Comment by JBou** [comment]
Ok danke! :D Ist dies auch der Fall wenn ein Spieler stirbt? Haben heute auch dort dieses Problem gesehen.

**Comment by JBou** [comment]
Wollte nochmal fragen ob du daran arbeitest. Wäre sehr wichtig für uns, wenn du das fixen könntest. Möchte nur wissen wie lange es noch dauert. Falls du keine Zeit hast ist kein Problem, würde nur gerne den Status wissen :D
MfG JBou

**Comment by Howaner** [comment]
Gefixxt.
Sorry, dass es so lange gedauert hat.

**Comment by JBou** [comment]
Kein Problem. Vielen Dank!
